### ISSUE TITLE
With preparse enabled, front-end asset uploads will not work

### ISSUE THREAD

**Issue by ryanbattles** [aelvan/Preparse-Field-Craft#23] opened 2016-11-15 20:50 UTC
Here's my scenario:

I have a matrix field where one of the matrix sub-fields is an asset upload to S3. I am using a front-end form to power this.

Now, I also have a preparse field for combining keywords from a handful of other text inputs on this section as well. 

When I am in the control panel, everything works as expected (matrix, asset upload, preparse)
When I am on the front-end of the site, everything works as expected, except uploading the asset fields, and this only occurs when I have a preparse field in that same section. When I delete the preparse field, the problem goes away.

What I know:

The file is actually being uploaded to S3, and it shows up as an asset in the control panel. However, the matrix row itself never really saves.

My guess is that there is some conflict on the back-end with this scenario, perhaps a timeout is happening, not sure. My craft.log doesn't display any errors...but the matrix row definitely doesn't save when I upload an image, as long as I am preparsing something in that section.

**Comment by aelvan** [comment] 2016-11-15 22:27
I've never tried using a preparse field in a front-end form, but I guess it should work there too. Could you supply some code showing how this is set up on the front-end, so I can set up a test case? 

Also, does this really have anything to do with the asset field or the fact that the assets are on S3? What happends if you remove the asset field, does the matrix block get saved? It sounds more like something going wrong in onSaveElement which preparse latches onto, which prevents the element from saving. Have you tried removing the twig code in the preparse field, does it save then?

**Comment by ryanbattles** [comment] 2016-11-16 14:49
Thanks for the reply! Yes, the preparse field does work beautifully on the front-end form, except when I upload :)

Here is a snippet of how my front-end form works:
```
<form method="post" accept-charset="UTF-8" enctype="multipart/form-data">
  
  {% if entry %}
    <input type="hidden" name="entryId" value="{{ entry.id }}">
  {% endif %}

  <input type="hidden" name="action" value="entries/saveEntry">
  <input type="hidden" name="redirect" value="{{ craft.request.getPath() }}?submitted=y">
  <input type="hidden" name="sectionId" value="10">
  <input type="hidden" name="enabled" value="1">
  {{ getCsrfInput() }}

  {# other text fields #}

  <table>
    <tr>
      <input type="hidden" name="fields[facilityUploads][new1][type]" value="upload">
      <input type="hidden" name="fields[facilityUploads][new1][enabled]" value="1">
      <td class="name">
        <input type="text" name="fields[facilityUploads][new1][fields][uploadTitle]" class="form-control" placeholder="Document Title" data-rule-doctitle="true" />
      </td>
      <td class="actions">
        <input type="file" name="fields[facilityUploads][new1][fields][file]" data-rule-docfile="true" />
        <a href="#" class="text-danger remove-existing-upload"><i class="fa fa-trash" aria-hidden="true"></i></a>
      </td>
    </tr>

    {# more matrix rows here like above if customer clicks "add" #}

  </table>

  {# other text fields & submit #}

</form>
```

To provide more context, I can actually submit the matrix fields okay as long as I only fill in the text input (uploadTitle), but don't try to upload an attachment. Also, ironically, I have another file upload field on the front-end form and that works just fine. It really is just with a file upload, within matrix, paired with a preparse field that causes the matrix to save nothing.

- If I don't upload anything into a matrix field, it works.
- If I remove the preparse field, it works.
- If I upload into the matrix field and have a preparse field...it doesn't :)

Here is the preparse field template I am using (via external file):

```
{% spaceless %}
  {{ entry.title }}
  {{ entry.parentCompany.first().title }}
  {{ entry.facilityDescription }}
  {{ entry.contactName }}
  {{ entry.address }}
  {% for tag in entry.acceptedWaste %}{{ tag.title }} {% endfor %}
{% endspaceless %}
```

I'm basically using that so I can have a more universal search that crams in keywords from multiple fields into one.

I understand that this is so niche and specific that I don't really expect you to take too much time for it, unless you are curious and want to :) I'll keep running tests and setting up isolated examples to see if I can narrow down the issue further. Thanks!

**Comment by KDLees** [comment] 2017-03-07 10:27
I have encountered a similar issue with front end file uploads and preparse fields (a very useful plugin by the way).

The issue I had arises because the `setContentFromPost` call made by the preparse plugin after the entry has been saved processes the uploaded files twice, which causes the file validation to fail.

In more detail:

- A front end form with file uploads is posted to craft, the files processed and the entry saved.
- If there are preparse fields on the field layout the preparse plugin runs and sends the computed fields to` setContentFromPost`.
- The `setContentFromPost` method loops through the entry's field layout calling `prepValueFromPost` on the fields that preparse has sent to it, however it also calls `prepValueFromPost` again on any assets field included on the form that also has an uploaded file in the current POST from the front end.
- When `prepValueFromPost` processes the file uploads again, the files it tries to process (in app/storage/runtime/temp) are zero sized and fail the image checks built into Craft.

To get round this I added a couple of lines before the `setContentFromPost` call in PreparseFieldPlugin.php:

```
if (!empty($content)) {  
  //fix file uploads being processed twice by craft, which causes an error.
  unset($_FILES);
  UploadedFile::reset();
                    
  $element->setContentFromPost($content);
```

These clear the posted file uploads and prevents them being processed twice.

**Comment by timkelty** [comment] 2017-03-13 18:13
Just burned several hours on this as well. I can confirm that with preparse enabled, front-end asset uploads will not work, for the reasons @KDLees outlined.

**Comment by ryanbattles** [comment] 2017-03-13 18:21
I updated the title to remove the references to Matrix and S3, since they are not a core part of the issue (so others might find this answer).

**Comment by shornuk** [comment] 2017-03-13 18:57
Yep, had this as well today. Spent ages trying to debug. Good catch on this. The fix posted seems to have worked so hopefully it can be rolled in!

**Comment by aelvan** [comment] 2017-03-13 20:45
> The setContentFromPost method loops through the entry's field layout calling prepValueFromPost on the fields that preparse has sent to it, however it also calls prepValueFromPost again on any assets field included on the form that also has an uploaded file in the current POST from the front end.
> 
> When prepValueFromPost processes the file uploads again, the files it tries to process (in app/storage/runtime/temp) are zero sized and fail the image checks built into Craft.

I can apply the patch. but to me this sounds like a bug in Craft. At least if it happends only when uploading from a front-end form, and not when doing the same thing in the admin. I think I want to check with P&T first, since I'm guessing it could have unintentional side-effects to reset file uploads like that.

@KDLees Ref the question from @timkelty , did you add it to elements.onBeforeSaveElement or elements.onSaveElement ?

**Comment by KDLees** [comment] 2017-03-13 22:32
I only added the fix to elements.onSaveElement.

I would also say that this is a bug in Craft, according to the documentation the setContentFromPost method should only process the fields sent to it. I only applied the fix in preparse so I could maintain automatic Craft updates.

It doesn't happen in admin because files associated with assets fields have already been uploaded when an entry is saved.

**Comment by timkelty** [comment] 2017-03-14 11:11
Agreed, I would hold off merging until P&T weighs in. /cc @brandonkelly @takobell

**Comment by brandonkelly** [comment] 2017-03-14 13:37
cc @andris-sevcenko

**Comment by aelvan** [comment] 2017-03-14 13:38
I'll set up a minimal test case and send to P&T later today.

**Comment by KDLees** [comment] 2017-03-14 16:03
If it helps the problem is with the `elseif` on [line 895](https://github.com/pixelandtonic/Craft-Release/blob/master/app/models/BaseElementModel.php#L895) in app/models/BaseElementModel.php

If a field is on a layout this line checks for uploads even if the field is not amongst those fields passed to `setContentFromPost`.

**Comment by timkelty** [comment] 2017-03-22 18:06
> did you add it to elements.onBeforeSaveElement or elements.onSaveElement ?

@aelvan I had to add it to `elements.onBeforeSaveElement` (in the event I was using the process before save option) as well.

**Comment by aelvan** [comment] 2017-04-03 15:45
P&T has implemented a fix for this which will come to Craft soonish.

**Comment by aelvan** [comment] 2017-04-09 14:31
The fixed has been implemented in [Craft 2.6.2969](https://craftcms.com/changelog#2-6-2969). Closing.

**Closed by aelvan** 2017-04-09 14:31 UTC

**Comment by aaronwaldon** [comment] 2017-09-17 19:30
I am still running into this issue on the latest version of Craft (2.6.2990). So glad I found the fix on this page! It is the only thing that worked for me out of the couple of hours that I spent troubleshooting. 

I created a pull request based on the code from @KDLees

**Comment by ryanbattles** [comment] 2017-11-30 19:49
Thanks @aaronwaldon (and @KDLees), I was still running into this with the latest version of Craft (2.6.2999) and Preparse (0.3.6) as well. I grabbed the adjustment from your pull request and now it is working flawlessly. 👍

**Comment by i-just** [comment] 2019-04-04 13:59
In Craft 3 a fix for this issue (more specifically the resetUloads() method in the src/PreparseField.php file) is causing the `symfony/http-foundation/Request::createFromGlobals()` method to fail as it cannot find `$_FILES` superglobal. In case of my website that causes serious problems when trying to make a payment.

Would changing `unset($_FILES)` to `$_FILES = []` still provide a fix for this issue? Second option doesn't break the `createFromGlobals()`.
